# Generated by Django 4.0.5 on 2022-06-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Profile',
            new_name='sender',
        ),
    ]
